In [1]:
# 1D array of numbers 1-10
import numpy as np

array = np.array([0,1,2,3,4,5,6,7,8,9])

print(array)

[0 1 2 3 4 5 6 7 8 9]


In [26]:
# 33×3 NumPy array of all Boolean value Trues
import numpy as np
ones = np.ones(9)

newArray = ones.reshape(3,3)

print(newArray)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [51]:
# Extract all odd numbers from array of 1 - 10
import numpy as np

array1 = np.arange(1,11)

arrayOdd = array1[array%2==1]

print(arrayOdd)








[1 3 5 7 9]


In [53]:
# Replace all odd numbers in an array of 1 10 with the value 1
import numpy as np

array1 = np.arange(1,11)
arrayNew = np.where(array1%2==1, -1, array1)

print(arrayNew)



[-1  2 -1  4 -1  6 -1  8 -1 10]


In [54]:
# Convert a 1D array to a 2D array with 2 rows

import numpy as np

array = np.array([0,1,2,3,4,5,6,7,8,9])

arrayShape = array.reshape(2,5)

print(arrayShape)




[[0 1 2 3 4]
 [5 6 7 8 9]]


In [59]:
# Create two arrays a and b, stack these two arrays vertically use the np.dot and
# np.sum to calculate totals

import numpy as np

array1 = np.array([1,2,3,4])
array2 = np.array([5,6,7,8])

arVstack = np.vstack((array1, array2))

print(arVstack)

c = np.dot(array1, array2)
print(c)

d = np.sum(arVstack)
print(d)




[[1 2 3 4]
 [5 6 7 8]]
70
36


In [ ]:
# In two arrays a (1,2,3,4,5) and b (4,5,6,7,8,9) remove all repeating items present in array b

import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8,9])


